### ISSUE TITLE
US1 - CRIA HOME SISTEMA

### ISSUE THREAD

**Issue by Anaritamed** [Anaritamed/click-jogos#1]
# Descrição
Desenvolver a tela inicial do sistema Click Jogos, que será a primeira interface visual com a qual os usuários interagirão ao acessar a aplicação.

## Tasks
- [x] Definir design da tela inicial.
- [x] Criar tela inicial.
- [x] Adicionar lógica de funcionamento
