### ISSUE TITLE
US2 - CRIA JOGO DA VELHA

### ISSUE THREAD

**Issue by Anaritamed** [Anaritamed/click-jogos#2]
# Descrição
Descrição: Implementar o jogo da velha, permitindo que dois jogadores possam jogar de forma interativa na interface do sistema. O jogo da velha deve seguir as regras tradicionais.

## Tasks

- [x] **Interface** - Desenvolver um tabuleiro 3x3, composto por células onde os jogadores poderão marcar "X" ou "O". 
  - Incluir indicadores de turno para mostrar de quem é a vez de jogar.
  - Adicionar um botão para reiniciar o jogo a qualquer momento. _(A discutir)_
- [x] **Validação** - Garantir que um jogador não possa jogar em uma célula já ocupada.
  - O jogo deve reconhecer e finalizar corretamente em caso de empate (quando todas as células estiverem preenchidas e ninguém vencer).
- [x] **Experiência do Usuário** - Exibir mensagens claras e intuitivas para indicar o estado atual do jogo.
  - Quem venceu, se houve empate, de quem é a vez, etc.
- [x] **Testes** - Realizar testes manuais para verificar a usabilidade e a experiência geral do jogo.
  - Jogar avaliando todos os caminhos possíveis: vitória, derrota e empate.
- [ ] Adicionar a funcionalidade para que o jogador possa sair do jogo atual e retornar ao menu principal.
